### ISSUE TITLE
Deleted package detected


### ISSUE THREAD

**Issue by ashishbijlani** [EasyJailbreak/EasyJailbreak#1]
I'm a Cyber Security researcher and developer of PackjGuard [1] to address open-source software supply chain attacks.

# Issue

During my research, I detected a _deleted package_ in this repository.

# Details

Specifically, the package `easyjailbreak` mentioned in file `README` at line 33 does not exist on the public **PyPI** registry. A bad actor can hijack this package to propagate malicious code.

# Impact

Not only your apps/services using `https://github.com/EasyJailbreak/EasyJailbreak` repo code are vulnerable to this attack, but the users of your open-source Github repo could also fall victim.

You could read more about such attacks here: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

# Remediation
         
Please highlight this in file README and register a placeholder package for `easyjailbreak` on public PyPI soon to remediate.

To automatically fix such issues in future, please install PackjGuard Github app [1].
                                         
Thanks!    

1. PackjGuard is a Github app that monitors your repos 24x7, detects vulnerable/malicious/risky open-source dependencies, and creates pull requests for auto remediation: https://github.com/marketplace/packjguard

**Comment by WalterSumbon** [comment]
Thank you for bringing this to our attention. The `easyjailbreak` package has now been re-uploaded to the PyPi registry. 

We appreciate your diligence and the valuable insights provided regarding open-source software supply chain security.
