### ISSUE TITLE
HI could u share the result of jailbreaking prompts, thx!

### ISSUE THREAD

**Issue by zichuan-liu** [EasyJailbreak/EasyJailbreak#11]
Computing resources are too expensive and some code takes a long time to run, could you open source the results?

**Comment by zichuan-liu** [comment]
i found it! ,thx, but Why do the open source calculations not match the tables, e.g. Cipher did not succeed 61% in llama2

**Comment by A1pacin0** [comment]
Hi！I also need the the result of jailbreaking prompts,but i didn't find it yet. Could you please share it?THX!
