### ISSUE TITLE
Varied Evaluator for Different Attacks

### ISSUE THREAD

**Issue by xirui-li** [EasyJailbreak/EasyJailbreak#13]
For different attackers, the evaluation is implemented according to their papers, including string matching, gpt evaluation ... . I am wondering, are the results from your [Leaderboard](http://easyjailbreak.org/leader-board) under same evaluation or different evaluations.

If the results are under same evaluation, which evaluation are you applying on?

Thanks in advance!

**Comment by BeyonderXX** [comment]
Sure, all the results are evaluated under the same criteria. 
We use GPT-4 for evaluation, and the evaluation set is Advbench.
