### ISSUE TITLE
How to resume from previous attack

### ISSUE THREAD

**Issue by verazuo** [EasyJailbreak/EasyJailbreak#15]
Hi,

Thanks for building this great project!

I am curious if easyjailbreak will support a resume feature, especially since attacks like GCG can take several days to complete?

Best,

**Comment by BeyonderXX** [comment]
Hi,

Good question!  Currently, our framework is indeed capable of handling this. You can set a smaller number of optimization iterations for the first time. Our framework can save the final results, whether successful or not. For subsequent iterations, simply re-enter the previously saved prompt as the initial dataset.

We plan to add an interface soon that will directly provide a loadable dataset.

Xiao Wang

**Comment by verazuo** [comment]
Cool! Thx for the explanation and look forward to the coming function!
