### ISSUE TITLE
GPTFuzzer isn't running 

### ISSUE THREAD

**Issue by EngSalem** [EasyJailbreak/EasyJailbreak#22]
I tried to run examples/run_gptfuzzer.py on 10 examples of the advbench

I was getting error: 
"Conversation" has no attribute template

I tried to sovle this by modifying the "/EasyJailbreak/tree/master/easyjailbreak/models/huggingface_model.py" 
line 57  to the following.
```
 self.conversation.roles = tuple(['### ' + r for r in self.conversation.roles])
```
The code now runs, but stalls after two iterations and won't proceed afterwards

**Comment by nitwtog** [comment]
The stalling after two iterations might be due to the fact that you set the hyperparameters to stop after two iterations, or it could be because the jailbreak attack has already been completed. You need to check this in conjunction with your output results and specific hyperparameters.

**Comment by dirtycomputer** [comment]
> I tried to run examples/run_gptfuzzer.py on 10 examples of the advbench
> 
> I was getting error: "Conversation" has no attribute template
> 
> I tried to sovle this by modifying the "/EasyJailbreak/tree/master/easyjailbreak/models/huggingface_model.py" line 57 to the following.
> 
> ```
>  self.conversation.roles = tuple(['### ' + r for r in self.conversation.roles])
> ```
> 
> The code now runs, but stalls after two iterations and won't proceed afterwards

same question
