### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by chrisng2008** [EasyJailbreak/EasyJailbreak#25]
![image](https://github.com/EasyJailbreak/EasyJailbreak/assets/72513336/42d8d69e-e884-47f8-b02d-7ed6e53089f9)

I got this error while running this demo script of  Load Dataset and initialize Seed part.

**Comment by nitwtog** [comment]
You need to pass some initialization parameters called possible_tokens. possible_tokens should be strings that will be randomly added to the seed jailbreak prompt. This function will randomly select some characters from them to form a long string, which will be used as the randomly initialized jailbreak prompt.
