### ISSUE TITLE
Code on generating harmful responses.

### ISSUE THREAD

**Issue by zhipeng-wei** [EasyJailbreak/EasyJailbreak#28]
I want to jailbreak models with your provided ["jailbreak prompts"](https://drive.google.com/file/d/1Im3q9n6ThL4xiaUEBmD7M8rkOIjw8oWU/view?usp=sharing). However, the LLMs often give responses that are different from the provided "target_responses". Could you share the code in generating these harmful responses?

**Comment by nitwtog** [comment]
Hello, the code we ran in our experiments is included in the Python files within the examples folder. We have aligned the settings with the default hyperparameters provided in the paper as closely as possible.
