### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Hephaestusxg** [EasyJailbreak/EasyJailbreak#4]
I would like to inquire about the dataset on Hugging Face, which is in the Parquet format. However, our server is unable to connect to a VPN. How can I load the dataset locally? When running the program, I encounter the RuntimeError: cutlassF: no kernel found to launch! What should I do about this?

**Comment by WalterSumbon** [comment]
For local dataset files, you can directly load them using `easyjailbreak.datasets.JailbreakDataset(dataset_file_path, local_file_type=...)`. easyjailbreak utilizes the `load_dataset` function from the Hugging Face `datasets` library to load the dataset, as seen in the code here: https://github.com/EasyJailbreak/EasyJailbreak/blob/178b588ca8d13065d12acb17d76e4973b5bdde79/easyjailbreak/datasets/jailbreak_datasets.py#L48

**Comment by Hephaestusxg** [comment]
> For local dataset files, you can directly load them using `easyjailbreak.datasets.JailbreakDataset(dataset_file_path, local_file_type=...)`. easyjailbreak utilizes the `load_dataset` function from the Hugging Face `datasets` library to load the dataset, as seen in the code here:
> 
> https://github.com/EasyJailbreak/EasyJailbreak/blob/178b588ca8d13065d12acb17d76e4973b5bdde79/easyjailbreak/datasets/jailbreak_datasets.py#L48

sry ..
I have another question I would like to ask.Is this project not included in the evaluation of results, such as ASR calculations and the like? Because the original attack method projects all included eval.py and the like.

**Comment by WalterSumbon** [comment]
Check this out: [metric_ASR.py](https://github.com/EasyJailbreak/EasyJailbreak/blob/7b94ff64578beb537254251e60534e005876e8da/easyjailbreak/metrics/Metric/metric_ASR.py)
