### ISSUE TITLE
KeyError: 'zero-shot'

### ISSUE THREAD

**Issue by zky001** [EasyJailbreak/EasyJailbreak#5]
![image](https://github.com/EasyJailbreak/EasyJailbreak/assets/9131265/5d054413-5a07-4c1c-9344-a3e82af7e947)
examples\run_gptfuzzer.py", line 15, in <module>
    judge_eval_model = HuggingfaceModel(model=judge_model, tokenizer=judge_tokenizer, model_name='zero-shot')
\models\huggingface_model.py", line 46, in __init__
    self.conversation = get_conv_template(model_name)
fastchat\conversation.py", line 412, in get_conv_template
    return conv_templates[name].copy()
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'zero-shot'

**Comment by zky001** [comment]
我也是0.2.34的fschat

**Comment by Hephaestusxg** [comment]
> 我也是0.2.34的fschat

你解决了么
