### ISSUE TITLE
Cost interval?

### ISSUE THREAD

**Issue by t0hka1** [EasyJailbreak/EasyJailbreak#7]
I am curious about the cost range for evaluating a single model using the GenerativeJudge method with the actual invocation of GPT-4-turbo-1106. Could you please provide me with an estimated range of costs for this service? Your assistance is greatly appreciated！

**Comment by nitwtog** [comment]
Thank you for your questions. In the assessment, we employed GenerativeJudge, which is based on GPT-4-turbo-1106, and the expense for evaluating 100 responses from the target model was approximately 0.5 US dollars.

**Comment by t0hka1** [comment]
Thank you for your answer！
