### ISSUE TITLE
running so slowly

### ISSUE THREAD

**Issue by zh190920** [EasyJailbreak/EasyJailbreak#8]
Why are all evaluations running so slowly, is this normal or do some parameters need to be adjusted? Thanks for the answer

**Comment by BeyonderXX** [comment]
Hi,

Thank you for bringing this up. 
Regarding the methods of Human Design and Longtail Encoding, they indeed run quite efficiently. However, when it comes to Prompt Optimization methods, the performance noticeably slows down, as outlined in our paper.

1. The speed of the supported methods is consistent with what is reported in the original papers, indicating that the slower speed is an inherent drawback of the Prompt Optimization approach.
2. The primary reason for the slowdown is that Prompt Optimization often requires numerous optimization iterations. Each iteration may involve backpropagation (where applicable), text generation, and answer evaluation, which can be time-consuming processes.
3. Although we've implemented optimizations to improve speed, such as utilizing vLLM lib for faster inference, these improvements have not resulted in a significant qualitative increase in speed.

Xiao Wang
