### ISSUE TITLE
只能用于语言模型吗，如果要在多模态模型中使用，我需要修改哪些代码

### ISSUE THREAD

**Issue by qianshanwei** [EasyJailbreak/EasyJailbreak#9]
RT，谢谢您的工作，期盼您的回复

**Comment by BeyonderXX** [comment]
你好！ 
感谢关注，目前只适用于LLM。
多模态模型的安全评测，可能会在后面大版本中更新。

Xiao Wang

**Comment by qianshanwei** [comment]
> 你好！ 感谢关注，目前只适用于LLM。 多模态模型的安全评测，可能会在后面大版本中更新。
> 
> 王潇

谢谢回复，如果需要我自行修改代码的话，应该需要修改哪一部分呢，可以给一点提示吗

**Comment by LemXiong** [comment]
你好！ 感谢关注！
如果需要使用多模态数据的话需要：
1.修改datasets下面的instance和jailbreak_datasets：包括添加变量存储其他模态信息，新增对应的load_xxx函数等
2.修改models中的generate，增加对非文本模态的处理
3.如果输出中也包含非文本模态且需要使用到constraint, Evaluator, mutation, 则也需要在对应类其中加入对非文本模态的处理

**Comment by LemXiong** [comment]
> > 你好！ 感谢关注，目前只适用于LLM。 多模态模型的安全评测，可能会在后面大版本中更新。
> > 王潇
> 
> 谢谢回复，如果需要我自行修改代码的话，应该需要修改哪一部分呢，可以给一点提示吗

你好！ 感谢关注！
如果需要使用多模态数据的话需要：

1.修改datasets下面的instance和jailbreak_datasets：包括添加变量存储其他模态信息，新增对应的load_xxx函数等
2.修改models中的generate，增加对非文本模态的处理
3.如果输出中也包含非文本模态且需要使用到constraint, Evaluator, mutation, 则也需要在对应类其中加入对非文本模态的处理

**Comment by qianshanwei** [comment]
我希望可以人为修改自己越狱攻击相关的内容，可以吗

**Comment by LemXiong** [comment]
> 我希望可以人为修改自己越狱攻击相关的内容，可以吗

可能没有太理解你的意思。如果是指对攻击流程进行修改/优化的话，是可以的，可以参考我们的attacker和examples的写法，核心就是数据/模型的加载和组件的拼接组合。
